language: cpp
sudo: required
dist: trusty
compiler: gcc

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt571-trusty
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install qt5-default qttools5-dev-tools
 
script:
  - source /opt/qt57/bin/qt57-env.sh
  - make tests
