language: cpp
sudo: required
dist: bionic
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++

before_install:
  - pip install --user cpp-coveralls
  
install:
  - sudo apt-get install qt5-default qt5-qmake
  
script:
  - make before
  - make tests
  - make tarotclub-srv

# Later: run unit tests  
#  - ./build/tests/release/unit_tests

#after_success:
#  - cd ./build/tests/release
#  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

